// Shared by the Markdown engine (raw inline HTML) and the rehype entry point.
/** Inline formatting elements that join the surrounding sentence, so quotes pair across them. */
export const transparent = new Set([
  'em',
  'strong',
  'b',
  'i',
  'u',
  's',
  'del',
  'ins',
  'mark',
  'small',
  'sub',
  'sup',
  'span',
  'font',
  'abbr',
  'cite',
  'dfn',
  'q',
  'time',
  'data',
  'bdi',
  'bdo',
  'label',
  'nobr',
  'ruby',
]);
