import { Fragment, type CSSProperties, type ReactNode } from 'react';

import { kerning, ligatures } from './kerning';

/*
  Hand kerning for Hedvig Letters Serif headings. Display type set at text spacing reads loose,
  so kerning.ts, generated by scripts/measure-hedvig-kerning.py from the outlines themselves,
  pulls each pair toward a common clearance and keeps every pair at least 0.02em apart. Each
  value is letter-spacing after the first glyph of its pair. A span starts a new text run, which
  drops the font's own kern on both sides of it, so each value includes that kern. Rerun the
  script whenever a <Kern> heading changes.
*/

/** Set one word, spacing its kerned pairs. */
function word(text: string, offset: number) {
  const parts: ReactNode[] = [];
  let run = '';
  for (let i = 0; i < text.length; i++) {
    // A letter inside a ligature stays in its run, or the ligature would break.
    const inLigature =
      ligatures.has(text.slice(i - 1, i + 1)) || ligatures.has(text.slice(i, i + 2));
    const space = inLigature ? undefined : kerning[text.slice(i, i + 2)];
    if (space === undefined) {
      run += text[i];
      continue;
    }
    if (run) parts.push(<Fragment key={`r${offset + i}`}>{run}</Fragment>);
    run = '';
    parts.push(
      <span
        key={offset + i}
        className="kern"
        style={{ letterSpacing: `${space}em` } as CSSProperties}
      >
        {text[i]}
      </span>,
    );
  }
  if (run) parts.push(<Fragment key={`r${offset + text.length}`}>{run}</Fragment>);
  return parts;
}

/**
 * Set a heading's text, spacing the pairs in `kerning` by hand. A kerned word is kept whole,
 * since an element boundary inside it would otherwise let the line break there.
 */
export function Kern({ children }: { children: string }) {
  const parts: ReactNode[] = [];
  let offset = 0;
  for (const piece of children.split(/( )/)) {
    const next = `${piece}${children[offset + piece.length] ?? ''}`;
    if (piece === ' ') {
      const space = kerning[next];
      parts.push(
        space === undefined ? (
          ' '
        ) : (
          <span
            key={offset}
            className="kern"
            style={{ letterSpacing: `${space}em` } as CSSProperties}
          >
            {' '}
          </span>
        ),
      );
    } else if (piece) {
      const kerned = [...piece.slice(0, -1)].some((_, i) => piece.slice(i, i + 2) in kerning);
      parts.push(
        kerned ? (
          <span key={offset} className="kern-word">
            {word(piece, offset)}
          </span>
        ) : (
          piece
        ),
      );
    }
    offset += piece.length;
  }
  return <>{parts}</>;
}
