import { Fragment, type CSSProperties, type ReactNode } from 'react';

/**
 * Hand kerning for Hedvig Letters Serif at display sizes, in em. Each value is added after the
 * first glyph of the pair so the two outlines keep at least 0.02em of clear space at optical
 * size 24. A span starts a new text run, which drops the font's own kern on both sides of it, so
 * each value includes that kern. Generated by scripts/measure-hedvig-kerning.py; rerun it with
 * every serif heading when one changes.
 */
export const kerning: Record<string, number> = {
  yw: 0.026,
  ry: 0.022,
  ty: 0.019,
  yp: 0.009,
  fu: 0.006,
  al: 0.005,
  vi: 0.004,
  wr: 0.003,
  wn: 0.003,
  // These only restore the font's kern where a span above broke the run.
  iv: -0.007,
  ow: -0.021,
  ' w': -0.031,
  Tr: -0.069,
};

/** Set one word, spacing its kerned pairs. */
function word(text: string, offset: number) {
  const parts: ReactNode[] = [];
  let run = '';
  for (let i = 0; i < text.length; i++) {
    const space = kerning[text.slice(i, i + 2)];
    if (space === undefined) {
      run += text[i];
      continue;
    }
    if (run) parts.push(<Fragment key={`r${offset + i}`}>{run}</Fragment>);
    run = '';
    parts.push(
      <span
        key={offset + i}
        className="kern"
        style={{ letterSpacing: `${space}em` } as CSSProperties}
      >
        {text[i]}
      </span>,
    );
  }
  if (run) parts.push(<Fragment key={`r${offset + text.length}`}>{run}</Fragment>);
  return parts;
}

/**
 * Set a heading's text, spacing the pairs in `kerning` by hand. A kerned word is kept whole,
 * since an element boundary inside it would otherwise let the line break there.
 */
export function Kern({ children }: { children: string }) {
  const parts: ReactNode[] = [];
  let offset = 0;
  for (const piece of children.split(/( )/)) {
    const next = `${piece}${children[offset + piece.length] ?? ''}`;
    if (piece === ' ') {
      const space = kerning[next];
      parts.push(
        space === undefined ? (
          ' '
        ) : (
          <span
            key={offset}
            className="kern"
            style={{ letterSpacing: `${space}em` } as CSSProperties}
          >
            {' '}
          </span>
        ),
      );
    } else if (piece) {
      const kerned = [...piece.slice(0, -1)].some((_, i) => piece.slice(i, i + 2) in kerning);
      parts.push(
        kerned ? (
          <span key={offset} className="kern-word">
            {word(piece, offset)}
          </span>
        ) : (
          piece
        ),
      );
    }
    offset += piece.length;
  }
  return <>{parts}</>;
}
